import pickle

stmts = [
    ("This movie is fantastic! I loved every minute of it.", "Positive"),
    ("The acting in this movie is terrible. I couldn't even finish it.", "Negative"),
    ("I thought this movie was just okay. It didn't really stand out to me.", "Neutral"),
    ("This movie is one of the best I've seen in a long time. The story is gripping and the characters are well-developed.", "Positive"),
    ("I don't know why this movie has such great reviews. I found it boring and predictable.", "Negative"),
    ("I enjoyed this movie, but it's not one that I would watch again.", "Neutral"),
    ("The special effects in this movie are amazing! They really added to the overall experience.", "Positive"),
    ("I was really disappointed with this movie. The plot was confusing and the pacing was off.", "Negative"),
    ("I thought this movie was pretty good. It had some flaws, but overall it was enjoyable.", "Neutral"),
    ("I'm really enjoying this book, the characters are so well developed.", "Positive"),
    ("The traffic today was terrible, I got stuck in it for over an hour.", "Negative"),
    ("This new coffee shop has great atmosphere and even better coffee!", "Positive"),
    ("I'm feeling a bit under the weather today, I hope I'm not getting sick.", "Neutral"),
    ("I can't wait for the new season of my favorite TV show to come out!", "Positive"),
    ("I got lost on my way to the meeting this morning, it was really stressful.", "Negative"),
    ("That movie was so boring, I almost fell asleep in the theater.", "Negative"),
    ("I had a great time at the concert last night, the music was fantastic.", "Positive"),
    ("I'm not sure how I feel about this new job yet, it's still early days.", "Neutral"),
    ("The customer service at that store was amazing, they went above and beyond to help me.", "Positive"),
    ("I'm really anxious about this presentation, I hope I don't mess it up.", "Negative"),
    ("I just finished a great workout at the gym, I feel so energized!", "Positive"),
    ("I had a terrible headache all day, it was really hard to concentrate on anything.", "Negative"),
    ("That restaurant was a bit overpriced, but the food was really good.", "Neutral"),
    ("I'm so happy that I got the promotion, all my hard work paid off!", "Positive"),
    ("I'm really disappointed that my flight got cancelled, I was looking forward to my trip.", "Negative"),
    ("The weather today is perfect for a day at the beach!", "Positive"),
    ("I'm not sure if I should buy this dress, it's a bit expensive.", "Neutral"),
    ("The hotel we stayed at on our vacation was amazing, I never wanted to leave!", "Positive"),
    ("I had a really bad dream last night, it's been bothering me all day.", "Negative"),
    ("I just finished reading a great book, I can't wait to read more from this author.", "Positive"),
    ("I'm really frustrated with my coworker, they're always late to meetings.", "Negative"),
    ("That concert last night was terrible, the sound quality was really bad.", "Negative"),
    ("I'm so grateful for my supportive friends and family, they always have my back.", "Positive"),
    ("I'm feeling a bit overwhelmed with all my work, I need to take a break.", "Negative"),
    ("That pizza we had last night was delicious, I wish I could have it every day!", "Positive"),
    ("I'm not sure what to do this weekend, I'm feeling a bit bored.", "Neutral"),
    ("The customer service at that store was terrible, they were really rude to me.", "Negative"),
    ("I had a really productive day at work today, I got so much done!", "Positive"),
    ("I'm really nervous about the job interview tomorrow, I hope I can do well.", "Negative"),
    ("The play I saw last night was amazing, the actors were so talented!", "Positive"),
    ("I'm feeling a bit sick today, I think I might need to go to the doctor.", "Negative"),
    ("That new store that opened up has really cute clothes, I want to buy everything!", "Positive"),
    ("I'm not sure if I'm ready for this new responsibility at work, it's a lot of pressure.", "Neutral"),
    ("I am so happy today, the sun is shining and the birds are singing!", "Positive"),
    ("I can't believe I missed my train again, what a terrible day.", "Negative"),
    ("The food at that new restaurant was amazing, I'll definitely be going back.", "Positive"),
    ("I'm really nervous about this interview, I hope it goes well.", "Neutral"),
    ("That book was really boring, I struggled to finish it.", "Negative"),
    ("The concert last night was incredible, the energy was amazing!", "Positive"),
    ("I hate waking up early in the morning, it puts me in a bad mood.", "Negative"),
    ("I'm so excited for my vacation next week, I've been looking forward to it for months!", "Positive"),
    ("I'm disappointed that my team lost the game, but they played really well.", "Neutral"),
    ("The service at that restaurant was terrible, I wouldn't recommend it.", "Negative"),
    ("This music is so catchy and fun, it always puts me in a good mood.", "Positive"),    
    ("I had the worst experience at that hotel, I would never stay there again.", "Negative"),    
    ("I can't stop thinking about how delicious that meal was, it was a true culinary masterpiece.", "Positive"),    
    ("The customer service at that store was so helpful and friendly, it made my day.", "Positive"),    
    ("I was really bored with that book, it felt like nothing ever happened.", "Negative"),    
    ("I'm so glad I decided to take that vacation, it was exactly what I needed.", "Positive"),    
    ("I couldn't believe how rude that person was to me, it was completely uncalled for.", "Negative"),    
    ("That concert was amazing, it was one of the best performances I've ever seen.", "Positive"),    
    ("The traffic was so bad this morning, it took me twice as long to get to work.", "Negative"),    
    ("I thought that movie was really well done, the acting and cinematography were fantastic.", "Positive"),    
    ("I was really disappointed with that album, it didn't live up to my expectations at all.", "Negative"),    
    ("That museum exhibit was so interesting and informative, I learned so much.", "Positive"),    
    ("The service at that restaurant was terrible, I had to wait an hour for my food.", "Negative"),    
    ("I'm so happy for my friend, she just got engaged and I can't wait for the wedding.", "Positive"),    
    ("I was really frustrated with that class, I couldn't understand anything the professor was saying.", "Negative"),    
    ("That was such a fun night out, I had a great time with my friends.", "Positive"),    
    ("I was so disappointed with that game, my team lost and they didn't even play well.", "Negative"),    
    ("I love that park, it's so peaceful and relaxing to spend time there.", "Positive"),    
    ("I was really annoyed with that person, they kept interrupting me while I was trying to work.", "Negative"),    
    ("That performance was mediocre at best, I wouldn't recommend it to anyone.", "Negative")
]

with open('trainModel.pickle', 'wb') as f:
    pickle.dump(stmts, f)
